{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3c1dd208-f479-4967-8609-95dd8e5f4b04",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from sqlalchemy import create_engine\n",
    "from faker import Faker\n",
    "import random"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "db88ffd6-acc6-462a-bcf5-9a72dfcb29d5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Configuration\n",
    "database_url = \"mysql://root:1234@localhost/clinic\"\n",
    "table_sizes = {'Patients': 1000, 'Appointments': 2000, 'Messages': 3000, 'Services': 500, 'Treatment_Records': 2000, 'Visits': 2000}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "bccdafd5-f29b-4060-bc2a-14952091d4e1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create database connection\n",
    "engine = create_engine(database_url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "82924f95-675e-4df1-b0f4-31e2d6349f50",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Initialize Faker\n",
    "fake = Faker()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "f241f56c-fc87-48b5-8568-7320faac08c4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate data for Patients\n",
    "patients_data = {\n",
    "    'Patient_ID': range(1, table_sizes['Patients'] + 1),\n",
    "    'Name': [fake.name() for _ in range(table_sizes['Patients'])],\n",
    "    'DOB': [fake.date_of_birth(minimum_age=0, maximum_age=100) for _ in range(table_sizes['Patients'])],\n",
    "    'Address': [fake.address() for _ in range(table_sizes['Patients'])],\n",
    "    'Email': [fake.email() for _ in range(table_sizes['Patients'])]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "353e90af-e006-445b-88f0-8b107fdc3667",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate data for Appointments\n",
    "appointments_data = {\n",
    "    'Appointment_ID': range(1, table_sizes['Appointments'] + 1),\n",
    "    'Patient_ID': [random.randint(1, table_sizes['Patients']) for _ in range(table_sizes['Appointments'])],\n",
    "    'Date': [fake.date_this_year() for _ in range(table_sizes['Appointments'])],\n",
    "    'Time': [fake.time() for _ in range(table_sizes['Appointments'])],\n",
    "    'Purpose': [fake.sentence() for _ in range(table_sizes['Appointments'])]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "b3bfc8f1-c3d5-4adf-b600-f5765f236624",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate data for Messages linked to Appointments\n",
    "messages_data = {\n",
    "    'Message_ID': range(1, table_sizes['Messages'] + 1),\n",
    "    'Appointment_ID': [random.randint(1, table_sizes['Appointments']) for _ in range(table_sizes['Messages'])],\n",
    "    'Date': [fake.date_this_year() for _ in range(table_sizes['Messages'])],\n",
    "    'Type': [random.choice(['SMS', 'Email', 'Notification']) for _ in range(table_sizes['Messages'])],\n",
    "    'Content': [fake.paragraph() for _ in range(table_sizes['Messages'])]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "094b365c-0fba-4c70-8329-465e5939c06d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate data for Services\n",
    "services_data = {\n",
    "    'Service_ID': range(1, table_sizes['Services'] + 1),\n",
    "    'Name': [fake.bs() for _ in range(table_sizes['Services'])],\n",
    "    'Description': [fake.catch_phrase() for _ in range(table_sizes['Services'])]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "4f73f8d3-46bd-417b-89be-701e52ef6af4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate data for Treatment_Records\n",
    "treatment_records_data = {\n",
    "    'Record_ID': range(1, table_sizes['Treatment_Records'] + 1),\n",
    "    'Description': [fake.paragraph() for _ in range(table_sizes['Treatment_Records'])]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "3948c34b-f6bf-4faf-aaff-1566ade6a7a6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate data for Visits\n",
    "visits_data = {\n",
    "    'Visit_ID': range(1, table_sizes['Visits'] + 1),\n",
    "    'Date': [fake.date_this_year() for _ in range(table_sizes['Visits'])],\n",
    "    'Time': [fake.time() for _ in range(table_sizes['Visits'])]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "e4651e1e-0cdf-423c-9321-ff9782ca4e9a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate data for Visit_Treatment\n",
    "visit_treatment_data = {\n",
    "    'Visit_ID': [random.randint(1, table_sizes['Visits']) for _ in range(table_sizes['Visits'])],\n",
    "    'Record_ID': [random.randint(1, table_sizes['Treatment_Records']) for _ in range(table_sizes['Visits'])],\n",
    "    'Service_ID': [random.randint(1, table_sizes['Services']) for _ in range(table_sizes['Visits'])]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "1a06e5d0-95d0-4dc1-ab10-7166cdee1192",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate data for Patient_Visits\n",
    "patient_visits_data = {\n",
    "    'Patient_ID': [random.randint(1, table_sizes['Patients']) for _ in range(table_sizes['Visits'])],\n",
    "    'Visit_ID': [i for i in range(1, table_sizes['Visits'] + 1)]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "3622cdee-da48-4102-a029-cd0feac48fa5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate data for Contact_Numbers\n",
    "contact_numbers_data = {\n",
    "    'Patient_ID': [random.randint(1, table_sizes['Patients']) for _ in range(table_sizes['Patients'])],\n",
    "    'Contact_number': [fake.phone_number() for _ in range(table_sizes['Patients'])]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "b72124fb-5ea2-4e33-95fa-f5cb74f12c67",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mrabd\\AppData\\Local\\Temp\\ipykernel_12472\\3769013509.py:2: UserWarning: The provided table name 'Patients' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  df_patients.to_sql('Patients', con=engine, if_exists='append', index=False)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "1000"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#sensitive\n",
    "\n",
    "#df_patients = pd.DataFrame(patients_data)\n",
    "#df_patients.to_sql('Patients', con=engine, if_exists='append', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "5b15372f-5433-4c59-becc-e024de87116a",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mrabd\\AppData\\Local\\Temp\\ipykernel_12472\\880559555.py:4: UserWarning: The provided table name 'Appointments' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  df_appointments.to_sql('Appointments', con=engine, if_exists='append', index=False)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "2000"
      ]
     },
     "execution_count": 29,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# senitove \n",
    "\n",
    "#df_appointments = pd.DataFrame(appointments_data)\n",
    "#df_appointments.to_sql('Appointments', con=engine, if_exists='append', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "0c7b6fbb-19d7-4bbc-b465-3cc8c1b2c375",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mrabd\\AppData\\Local\\Temp\\ipykernel_12472\\989393793.py:4: UserWarning: The provided table name 'Messages' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  df_messages.to_sql('Messages', con=engine, if_exists='append', index=False)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "3000"
      ]
     },
     "execution_count": 31,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# sensitive \n",
    "\n",
    "#df_messages = pd.DataFrame(messages_data)\n",
    "#df_messages.to_sql('Messages', con=engine, if_exists='append', index=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "6c06506d-6ded-4433-9241-063f334a5b85",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mrabd\\AppData\\Local\\Temp\\ipykernel_12472\\2372001682.py:2: UserWarning: The provided table name 'Services' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  df_services.to_sql('Services', con=engine, if_exists='append', index=False)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "500"
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# sensitive \n",
    "\n",
    "#df_services = pd.DataFrame(services_data)\n",
    "#df_services.to_sql('Services', con=engine, if_exists='append', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "b6f8d967-630a-475d-bd6b-04655d8f3759",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mrabd\\AppData\\Local\\Temp\\ipykernel_12472\\1127642772.py:2: UserWarning: The provided table name 'Treatment_Records' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  df_treatment_records.to_sql('Treatment_Records', con=engine, if_exists='append', index=False)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "2000"
      ]
     },
     "execution_count": 33,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# sensitive \n",
    "\n",
    "\n",
    "#df_treatment_records = pd.DataFrame(treatment_records_data)\n",
    "#df_treatment_records.to_sql('Treatment_Records', con=engine, if_exists='append', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "6580f21e-a209-4335-bd36-d247b55d8334",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mrabd\\AppData\\Local\\Temp\\ipykernel_12472\\3991210141.py:2: UserWarning: The provided table name 'Visits' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  df_visits.to_sql('Visits', con=engine, if_exists='append', index=False)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "2000"
      ]
     },
     "execution_count": 34,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# sensitive \n",
    "\n",
    "#df_visits = pd.DataFrame(visits_data)\n",
    "#df_visits.to_sql('Visits', con=engine, if_exists='append', index=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "435dc621-7cd8-4aeb-971f-4936a50dcb91",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mrabd\\AppData\\Local\\Temp\\ipykernel_12472\\177886560.py:2: UserWarning: The provided table name 'Visit_Treatment' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  df_visit_treatment.to_sql('Visit_Treatment', con=engine, if_exists='append', index=False)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "2000"
      ]
     },
     "execution_count": 35,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# sensitive \n",
    "\n",
    "#df_visit_treatment = pd.DataFrame(visit_treatment_data)\n",
    "#df_visit_treatment.to_sql('Visit_Treatment', con=engine, if_exists='append', index=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "5cda4577-7e1a-4c0e-bd89-c17de295a858",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mrabd\\AppData\\Local\\Temp\\ipykernel_12472\\92379673.py:2: UserWarning: The provided table name 'Patient_Visits' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  df_patient_visits.to_sql('Patient_Visits', con=engine, if_exists='append', index=False)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "2000"
      ]
     },
     "execution_count": 36,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# sensitive \n",
    "\n",
    "#df_patient_visits = pd.DataFrame(patient_visits_data)\n",
    "#df_patient_visits.to_sql('Patient_Visits', con=engine, if_exists='append', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "b6c66668-61d7-49c6-a0ea-0c6a6b03c184",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mrabd\\AppData\\Local\\Temp\\ipykernel_12472\\3591919196.py:2: UserWarning: The provided table name 'Contact_Numbers' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  df_contact_numbers.to_sql('Contact_Numbers', con=engine, if_exists='append', index=False)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "1000"
      ]
     },
     "execution_count": 38,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#sensitive\n",
    "\n",
    "#df_contact_numbers = pd.DataFrame(contact_numbers_data)\n",
    "#df_contact_numbers.to_sql('Contact_Numbers', con=engine, if_exists='append', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "afe37add-86aa-4b3d-ac09-5c1c2c6d48ad",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
